;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-insert-left-brace
	TeX-insert-backslash
	elpy-nav-backward-indent
	elpy-nav-forward-indent
	ess-indent-or-complete
	indent-for-tab-command
	markdown-outdent-or-delete
	org-beginning-of-line
	org-ctrl-c-ctrl-c
	org-cycle
	org-demote-subtree
	org-end-of-line
	org-kill-line
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	))
